name: Build and Test

on:
  push:
    branches: [dev]
  pull_requests:
    branches: [prod]
      

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - name: Android
            path: android-project
            build_command: ./gradlew assembleDebug
            test_command: ./gradlew testDebug
          - name: Spring
            path: spring-project
            build_command: mvn clean install --batch-mode --no-transfer-progress
            test_command: mvn test --batch-mode --no-transfer-progress

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build and Test
        run: |
          cd ${{ matrix.project.path }}
          ${{ matrix.project.build_command }}
          ${{ matrix.project.test_command }}