apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: aymane2001/project-pfe:latest
          envFrom:
            - configMapRef:
                name: postgres-config  # Name of the ConfigMap or Secret
          ports:
            - containerPort: 80