server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-healthily
    username: aymane
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


