server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-healthily
    username: aymane
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

image:
  upload:
    directory: uploads/

  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      enabled: true


project:
  video: videos/

